"""Regenerates src/res/font_inter_data.h and src/res/font_notosans_data.h from local TTF files.

Run with `uv run tools/make_fonts.py` from the repo root after downloading fresh copies of:
  - Inter Regular (static, not the variable font): https://github.com/rsms/inter/releases
    -> extras/ttf/Inter-Regular.ttf
  - Noto Sans Regular (static): https://github.com/notofonts/noto-fonts
    -> hinted/ttf/NotoSans/NotoSans-Regular.ttf
Both are SIL OFL 1.1 - copy each release's OFL.txt over src/res/font_*_LICENSE.txt too if it changed.

Place the two .ttf files next to this script (or pass paths on the command line) before running.

This shells out to cl.exe/g++/clang++ to build vendor/imgui/misc/fonts/binary_to_compressed_c.cpp
(same tool imgui itself recommends for embedding fonts) and runs it with -base85, which is what
keeps these fonts small in source form and lets them load via AddFontFromMemoryCompressedBase85TTF.
"""

import os
import shutil
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.join(SCRIPT_DIR, "..")
RES_DIR = os.path.join(REPO_ROOT, "src", "res")
B2C_SRC = os.path.join(REPO_ROOT, "vendor", "imgui", "misc", "fonts", "binary_to_compressed_c.cpp")

FONTS = [
    # (source ttf filename, imgui symbol name, output header stem, C++ constant name)
    ("Inter-Regular.ttf", "Inter", "font_inter_data.h", "kInterCompressedDataBase85"),
    ("NotoSans-Regular.ttf", "NotoSans", "font_notosans_data.h", "kNotoSansCompressedDataBase85"),
]


def build_b2c(build_dir: str) -> str:
    exe = os.path.join(build_dir, "b2c.exe" if os.name == "nt" else "b2c")
    compiler = shutil.which("cl") or shutil.which("g++") or shutil.which("clang++")
    if not compiler:
        sys.exit("No C++ compiler found (cl.exe / g++ / clang++) - open a 'Developer Command "
                 "Prompt' on Windows, or install g++/clang++, then re-run.")

    if os.path.basename(compiler).startswith("cl"):
        subprocess.run([compiler, "/nologo", "/O2", "/EHsc", B2C_SRC, f"/Fe:{exe}"],
                        cwd=build_dir, check=True)
    else:
        subprocess.run([compiler, "-O2", B2C_SRC, "-o", exe], check=True)
    return exe


def write_header(body_path: str, symbol: str, const_name: str, source_ttf: str, license_note: str, out_path: str) -> None:
    with open(body_path, "r") as f:
        body = f.read()
    body = body.replace(f"{symbol}_compressed_data_base85", const_name)

    header = f"""#pragma once

// Generated by tools/make_fonts.py from {os.path.basename(source_ttf)} ({license_note}) - do
// not hand-edit. Compressed with vendor/imgui/misc/fonts/binary_to_compressed_c.cpp -base85; load
// with io.Fonts->AddFontFromMemoryCompressedBase85TTF(AppFonts::{const_name}, size).

namespace AppFonts
{{
{body}
}}
"""
    with open(out_path, "w") as f:
        f.write(header)


def main() -> None:
    args = sys.argv[1:]
    with tempfile.TemporaryDirectory() as build_dir:
        b2c = build_b2c(build_dir)

        for ttf_name, symbol, header_name, const_name in FONTS:
            ttf_path = next((a for a in args if os.path.basename(a) == ttf_name), None) \
                or os.path.join(SCRIPT_DIR, ttf_name)
            if not os.path.isfile(ttf_path):
                sys.exit(f"Missing {ttf_name} - see this script's docstring for where to get it, "
                          f"then place it at {ttf_path} (or pass its path on the command line).")

            body_path = os.path.join(build_dir, f"{symbol}.txt")
            subprocess.run([b2c, "-base85", ttf_path, symbol], stdout=open(body_path, "w"), check=True)

            license_note = "SIL OFL 1.1 - see font_inter_LICENSE.txt" if symbol == "Inter" \
                else "SIL OFL 1.1 - see font_notosans_LICENSE.txt"
            out_path = os.path.join(RES_DIR, header_name)
            write_header(body_path, symbol, const_name, ttf_path, license_note, out_path)
            print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
