"""Regenerates src/res/font_*_data.h headers from local TTF files.

Run with `uv run tools/make_fonts.py` from the repo root after downloading fresh copies of:
  - Inter Regular/Bold/Italic/BoldItalic (static, not the variable font):
    https://github.com/rsms/inter/releases -> extras/ttf/Inter-{Regular,Bold,Italic,BoldItalic}.ttf
  - Noto Sans Regular/Bold/Italic/BoldItalic (static):
    https://github.com/notofonts/noto-fonts -> hinted/ttf/NotoSans/NotoSans-{Regular,Bold,Italic,BoldItalic}.ttf
Both are SIL OFL 1.1 - copy each release's OFL.txt over src/res/font_*_LICENSE.txt too if it changed.

Place the .ttf files next to this script (or pass paths on the command line) before running.

This shells out to cl.exe/g++/clang++ to build vendor/imgui/misc/fonts/binary_to_compressed_c.cpp
(same tool imgui itself recommends for embedding fonts) and runs it with -base85, which is what
keeps these fonts small in source form and lets them load via AddFontFromMemoryCompressedBase85TTF.
"""

import os
import shutil
import subprocess
import sys
import tempfile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.join(SCRIPT_DIR, "..")
RES_DIR = os.path.join(REPO_ROOT, "src", "res")
B2C_SRC = os.path.join(REPO_ROOT, "vendor", "imgui", "misc", "fonts", "binary_to_compressed_c.cpp")

WEIGHTS = [
    # (ttf filename suffix, b2c symbol suffix, C++ constant name suffix)
    ("Regular", "Regular", "Regular"),
    ("Bold", "Bold", "Bold"),
    ("Italic", "Italic", "Italic"),
    ("BoldItalic", "BoldItalic", "BoldItalic"),
]

FAMILIES = [
    # (ttf filename stem, b2c symbol prefix, output header stem, C++ constant name prefix, license note)
    ("Inter", "Inter", "font_inter_data.h", "kInter", "SIL OFL 1.1 - see font_inter_LICENSE.txt"),
    ("NotoSans", "NotoSans", "font_notosans_data.h", "kNotoSans", "SIL OFL 1.1 - see font_notosans_LICENSE.txt"),
]


def build_b2c(build_dir: str) -> str:
    exe = os.path.join(build_dir, "b2c.exe" if os.name == "nt" else "b2c")
    compiler = shutil.which("cl") or shutil.which("g++") or shutil.which("clang++")
    if not compiler:
        sys.exit("No C++ compiler found (cl.exe / g++ / clang++) - open a 'Developer Command "
                 "Prompt' on Windows, or install g++/clang++, then re-run.")

    if os.path.basename(compiler).startswith("cl"):
        subprocess.run([compiler, "/nologo", "/O2", "/EHsc", B2C_SRC, f"/Fe:{exe}"],
                        cwd=build_dir, check=True)
    else:
        subprocess.run([compiler, "-O2", B2C_SRC, "-o", exe], check=True)
    return exe


def main() -> None:
    args = sys.argv[1:]
    with tempfile.TemporaryDirectory() as build_dir:
        b2c = build_b2c(build_dir)

        for ttf_stem, symbol_prefix, header_name, const_prefix, license_note in FAMILIES:
            bodies = []
            source_names = []

            for ttf_suffix, symbol_suffix, const_suffix in WEIGHTS:
                ttf_name = f"{ttf_stem}-{ttf_suffix}.ttf"
                ttf_path = next((a for a in args if os.path.basename(a) == ttf_name), None) \
                    or os.path.join(SCRIPT_DIR, ttf_name)
                if not os.path.isfile(ttf_path):
                    sys.exit(f"Missing {ttf_name} - see this script's docstring for where to get it, "
                              f"then place it at {ttf_path} (or pass its path on the command line).")

                symbol = f"{symbol_prefix}{symbol_suffix}"
                const_name = f"{const_prefix}{const_suffix}CompressedDataBase85"

                # Run with cwd set to the ttf's own directory and pass just its basename - b2c
                # embeds whatever path string it's given verbatim into the "// File: ..." comment,
                # and an absolute path there would bake this machine's local disk layout into a
                # committed source file.
                body_path = os.path.join(build_dir, f"{symbol}.txt")
                subprocess.run([b2c, "-base85", os.path.basename(ttf_path), symbol],
                                cwd=os.path.dirname(ttf_path), stdout=open(body_path, "w"), check=True)

                with open(body_path, "r") as f:
                    body = f.read()
                body = body.replace(f"{symbol}_compressed_data_base85", const_name)
                bodies.append(body)
                source_names.append(os.path.basename(ttf_path))

            header = f"""#pragma once

// Generated by tools/make_fonts.py from {', '.join(source_names)} ({license_note}) - do
// not hand-edit. Compressed with vendor/imgui/misc/fonts/binary_to_compressed_c.cpp -base85; load
// with io.Fonts->AddFontFromMemoryCompressedBase85TTF(AppFonts::k...CompressedDataBase85, size).

namespace AppFonts
{{
{''.join(bodies)}
}}
"""
            out_path = os.path.join(RES_DIR, header_name)
            with open(out_path, "w") as f:
                f.write(header)
            print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
