"""Regenerates src/res/icon.ico and src/res/icon_data.h from scratch.

Run with `uv run tools/make_icon.py` from the repo root whenever the icon design changes.
Requires Pillow and a bold sans-serif TTF (DejaVu Sans Bold ships on most Linux distros;
on Windows/macOS point `FONT_PATH` at something like Arial Bold / Segoe UI Bold instead).
"""

import os

from PIL import Image, ImageDraw, ImageFont

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RES_DIR = os.path.join(SCRIPT_DIR, "..", "src", "res")

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

S = 1024  # supersampled, then downscaled per target size for anti-aliased edges


def render(size: int) -> Image.Image:
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    # Rounded-square badge in the same blue Dear ImGui uses for its default interactive/header
    # accent (~ (66,150,250)), deepened a touch for contrast against light and dark taskbars.
    bg = (35, 99, 226, 255)
    bg_edge = (24, 74, 179, 255)
    radius = int(S * 0.22)
    draw.rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, fill=bg)
    draw.rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, outline=bg_edge, width=int(S * 0.012))

    font = ImageFont.truetype(FONT_PATH, int(S * 0.52))
    text = "M"
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    tx = S * 0.30 - tw / 2 - bbox[0]
    ty = S * 0.52 - th / 2 - bbox[1]
    draw.text((tx, ty), text, font=font, fill=(255, 255, 255, 255))

    # Down-chevron - "markdown mark" M-arrow motif - to the right of the M.
    cx, cy, cw, ch = S * 0.72, S * 0.52, S * 0.20, S * 0.22
    pts = [
        (cx - cw / 2, cy - ch / 2),
        (cx, cy - ch / 2 + ch * 0.55),
        (cx + cw / 2, cy - ch / 2),
        (cx + cw / 2, cy - ch / 2 + ch * 0.30),
        (cx, cy + ch / 2),
        (cx - cw / 2, cy - ch / 2 + ch * 0.30),
    ]
    draw.polygon(pts, fill=(255, 255, 255, 255))

    return img.resize((size, size), Image.LANCZOS)


def write_ico(master: Image.Image) -> None:
    sizes = [256, 128, 64, 48, 32, 16]
    master.save(
        os.path.join(RES_DIR, "icon.ico"),
        format="ICO",
        sizes=[(s, s) for s in sizes],
    )


def write_icon_data_header(rgba_size: int = 48) -> None:
    im = render(rgba_size).convert("RGBA")
    w, h = im.size
    data = im.tobytes()

    lines = []
    for i in range(0, len(data), 20):
        chunk = data[i : i + 20]
        lines.append(", ".join(str(b) for b in chunk))
    body = ",\n    ".join(lines)

    header = f"""#pragma once

// Generated by tools/make_icon.py - do not hand-edit. Raw {w}x{h} RGBA8 pixel data for the
// app icon, baked in so we can call glfwSetWindowIcon() identically on Windows and (future)
// Linux without adding an image-decoding dependency just for this. Windows additionally gets
// res/icon.ico embedded as a resource (see res/app.rc) for the Explorer/taskbar icon.

namespace AppIcon
{{
    constexpr int kWidth = {w};
    constexpr int kHeight = {h};

    inline const unsigned char kPixelsRGBA[] = {{
    {body}
    }};
}}
"""
    with open(os.path.join(RES_DIR, "icon_data.h"), "w") as f:
        f.write(header)


if __name__ == "__main__":
    os.makedirs(RES_DIR, exist_ok=True)
    write_ico(render(256))
    write_icon_data_header(48)
    print(f"Wrote {RES_DIR}/icon.ico and {RES_DIR}/icon_data.h")
